// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/recipe-steps')({
  component: RecipeStepsListPage,
})

function RecipeStepsListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: recipe_steps */}
  return <div className="p-4">Loading recipe-steps...</div>
}
